import {GRID, MODULE_NAME as GRID_MODULE_NAME, MODULE_CORE_NAME as GRID_MODULE_CORE_NAME} from '@grid/view/definition';

export const MODULE_CORE_NAME = GRID_MODULE_CORE_NAME;
export const MODULE_NAME = `${GRID_MODULE_NAME}.plugin`;
export const PAGER_NAME = `${GRID}Pager`;
export const PROGRESS_NAME = `${GRID}Progress`;
export const SORT_BAR_NAME = `${GRID}SortBar`;
export const GROUP_BAR_NAME = `${GRID}GroupBar`;
export const PIVOT_BAR_NAME = `${GRID}PivotBar`;
export const SELECTION_BAR_NAME = `${GRID}SelectionBar`;
export const VISIBILITY_NAME = `${GRID}Visibility`;
export const COLUMN_CHOOSER_NAME = `${GRID}ColumnChooser`;
export const COLUMN_FILTER_NAME = `${GRID}ColumnFilter`;
export const COLUMN_FILTER_PANEL_NAME = `${GRID}ColumnFilterPanel`;
export const EDIT_FORM_NAME = `${GRID}EditForm`;
export const EDIT_FORM_PANEL_NAME = `${GRID}EditFormPanel`;
export const EDIT_FORM_EDITOR = `${GRID}EditFormEditor`;
export const EXPORT_NAME = `${GRID}Export`;
export const IMPORT_NAME = `${GRID}Import`;
export const ACTION_BAR_CORE_NAME = `${GRID}ActionBarCore`;
export const ACTION_BAR_NAME = `${GRID}ActionBar`;
export const ACTION_NAME = `${GRID}Action`;
export const ACTION_CORE_NAME = `${GRID}ActionCore`;

export const POPUP_NAME = `${GRID}Popup`;
export const POPUP_TRIGGER_NAME = `${GRID}PopupTrigger`;
export const POPUP_HEAD_NAME = `${GRID}PopupHead`;
export const POPUP_BODY_NAME = `${GRID}PopupBody`;
export const POPUP_PANEL_NAME = `${GRID}PopupPanel`;
export const POPUP_SERVICE = `${GRID}PopupService`;
export const POPUP_CLOSE_NAME = `${GRID}PopupClose`;